name: On Repository Dispatch
on:
  repository_dispatch:
    types: [new-release]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - name: Echo received payload version
        run: echo ${{ github.event.client_payload.packages[0].name }} - ${{ github.event.client_payload.packages[0].version }}
