name: On Repository Dispatch
on:
  repository_dispatch:
    types: [new-release]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - name: Echo received version from payload
        run: echo ${{ github.event.client_payload.packages[0].version }}
